#!/usr/bin/env bash
# Configure domain zone with subdomains

if [ $# -eq 1 ]; then
    for subdom in www lb-01 web-01 web-02; do 
	RECORD_TYPE=$(dig "$subdom"."$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
	DESTINATION=$(dig "$subdom"."$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
	echo "The subdomain $subdom is a $RECORD_TYPE record and points to $DESTINATION"
    done
elif [ $# -eq 2 ]; then
    RECORD_TYPE=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
    DESTINATION=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
fi
