#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install nginx -y
header="\\\n\tadd-header X-Served-By $HOSTNAME;\n"
sudo sed -i "36i $header" /etc/nginx/sites-available/default
sudo service nginx restart 
