#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# but after the 9-th iteration prints Hi
counter=1
while [ $counter -le 10 ]; do
    echo "Holberton School"
    ((counter++))
    if [ $counter -eq 10 ]; then
	echo "Hi"
    fi
done
